# Generated by Django 5.1.4 on 2026-08-07 19:19

import careers.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corridor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('consistency_dimensions', models.JSONField(blank=True, default=list)),
                ('escalation_routing', models.JSONField(blank=True, default=dict)),
                ('claims_vocabulary', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.CharField(db_index=True, default=careers.models._new_person_id, max_length=64, unique=True)),
                ('agent_name', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ('full_name', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=64)),
                ('city', models.CharField(blank=True, default='', max_length=255)),
                ('region', models.CharField(blank=True, default='', max_length=255)),
                ('country', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CorridorRung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64)),
                ('display_name', models.CharField(max_length=255)),
                ('requirement', models.CharField(choices=[('required', 'Required'), ('optional', 'Optional'), ('not_applicable', 'Not applicable')], max_length=20)),
                ('input', models.CharField(choices=[('identifier', 'Identifier'), ('identifier_with_jurisdiction', 'Identifier with jurisdiction'), ('oauth', 'Third-party login'), ('document_upload', 'Document upload'), ('screenshots', 'Screenshots')], max_length=40)),
                ('verifier', models.CharField(blank=True, max_length=64, null=True)),
                ('order', models.IntegerField(default=0)),
                ('corridor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rungs', to='careers.corridor')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('corridor', 'key')},
            },
        ),
        migrations.CreateModel(
            name='VerificationClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rung_key', models.CharField(db_index=True, max_length=64)),
                ('fact_type', models.CharField(max_length=64)),
                ('fact_value', models.CharField(max_length=500)),
                ('jurisdiction', models.CharField(blank=True, default='', max_length=255)),
                ('method', models.CharField(choices=[('primary_source', 'Primary source'), ('source_checked', 'Source checked'), ('org_vouched', 'Vouched by an organisation'), ('self_attested', 'Self attested')], max_length=32)),
                ('source_ref', models.CharField(blank=True, max_length=500, null=True)),
                ('evidence_hash', models.CharField(blank=True, max_length=128, null=True)),
                ('verifier', models.CharField(blank=True, max_length=64, null=True)),
                ('verifier_version', models.CharField(blank=True, max_length=64, null=True)),
                ('checked_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('superseded', 'Superseded'), ('failed', 'Failed'), ('disputed', 'Disputed')], default='active', max_length=20)),
                ('raw_finding', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('corridor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='careers.corridor')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='careers.person')),
            ],
            options={
                'ordering': ['-checked_at'],
                'indexes': [models.Index(fields=['person', 'rung_key', 'status'], name='careers_ver_person__7e3b73_idx')],
            },
        ),
    ]
