# Generated by Django 5.0.2 on 2026-08-13 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0002_corridorrung_route_signupcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='agent_name',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
