# Generated by Django 5.0.2 on 2026-08-24 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0003_alter_person_agent_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='corridorrung',
            name='jurisdictions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
