# Generated by Django 5.0.2 on 2026-08-29 07:39
"""
Room for negative checks — screening somebody against a list rather than
asserting a fact about them.

Additive, and the `shape` default is doing real work rather than filling a
column: every claim written before this migration is a fact about a person, so
backfilling them all to `asserts` is correct rather than merely convenient.
There is no data to migrate the other way, because nothing has ever written a
screen — this lands before the first screening adapter, deliberately, so that
one cannot ship into a table with nowhere to record what bounds its claims.

`source_as_of` and `matched_on` stay null and empty for facts. They only mean
anything for a screen, where they are what makes the result challengeable: the
date of the data searched, and the identifiers it was searched on.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0004_corridorrung_jurisdictions'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationclaim',
            name='matched_on',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='verificationclaim',
            name='shape',
            field=models.CharField(choices=[('asserts', 'A fact about the person'), ('screens', 'The result of searching a list')], default='asserts', max_length=16),
        ),
        migrations.AddField(
            model_name='verificationclaim',
            name='source_as_of',
            field=models.DateField(blank=True, null=True),
        ),
    ]
