# Generated by Django 5.0.2 on 2026-09-08 15:27

"""
Two identity-resolution fields, for exclusion screening only.

Both nullable/empty, and both stay that way for every existing person: the
product works without them. They exist to tell somebody apart from a
stranger with the same name on a federal exclusion list — a date of birth
resolves most collisions and, just as importantly, *clears* people, since a
shared name with a different date of birth is a different person.

`previous_names` because an exclusion is recorded under the name held at the
time, so screening only the current one misses the people worth finding.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0005_verificationclaim_matched_on_verificationclaim_shape_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='previous_names',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
