# Generated by Django 5.0.2 on 2026-10-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0006_person_date_of_birth_person_previous_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corridorrung',
            name='input',
            field=models.CharField(choices=[('identifier', 'Identifier'), ('identifier_with_jurisdiction', 'Identifier with jurisdiction'), ('oauth', 'Third-party login'), ('document_upload', 'Document upload'), ('screenshots', 'Screenshots'), ('automatic', 'Automatic')], max_length=40),
        ),
    ]
