# Generated by Django 5.0.2 on 2026-10-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0007_corridorrung_automatic_input'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='screening_consent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
