# Generated by Django 5.0.2 on 2026-08-10 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Student'), ('university', 'University'), ('institute', 'Institute'), ('candidate', 'Candidate'), ('superuser', 'Superuser')], max_length=20)),
                ('roles', models.JSONField(blank=True, default=list)),
                ('student_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('university_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('institute_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('person_id', models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
