# Generated by Django 5.0.2 on 2026-08-10 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PendingQuery',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('person_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('status', models.CharField(default='pending', max_length=32)),
                ('question', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
